apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xenova-cache
  namespace: knowledge-airflow
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
